{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Sample types:\n",
    "### 'Surf' IQR: 10-10 m\n",
    "### 'DCM' IQR: 30-75 m\n",
    "### 515: 515 m\n",
    "### 170: 170 m"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly_utils as pu\n",
    "import plotly.express as px\n",
    "import plotly.graph_objs as go\n",
    "import dash\n",
    "import json\n",
    "from dash import dcc, html\n",
    "from dash.dependencies import Input, Output\n",
    "import dash_bootstrap_components as dbc\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "px.set_mapbox_access_token(os.getenv('MAPBOX_ACCESS_TOKEN'))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Load data\n",
    "data_16S = pd.read_csv('NCOG_21_16S_redo2_asv_count_tax.tsv', sep='\\t')\n",
    "data_18Sv4 = pd.read_csv('NCOG_18sV4_asv_count_tax.tsv', sep='\\t')\n",
    "data_18Sv9 = pd.read_csv('NCOG_18sV9_asv_count_tax_S.tsv', sep='\\t')\n",
    "data_meta = pd.read_csv('NCOG_sample_log_DNA_stvx_meta_2014-2020_mod.tsv', sep='\\t')\n",
    "\n",
    "# Lat and Lon center for plots\n",
    "cal_coast_center = dict(\n",
    "    lat=np.mean([min(data_meta['Lat_Dec']), max(data_meta['Lat_Dec'])]),\n",
    "    lon=np.mean([min(data_meta['Lon_Dec']), max(data_meta['Lon_Dec'])])\n",
    ")\n",
    "\n",
    "# Environmental variables and sample types\n",
    "env_var_cols = ['T_degC', 'Salnty', 'O2ml_L', 'PO4ug', 'SiO3ug', 'NO3ug', 'NH3ug', 'ChlorA', 'IntC14', 'NCDepth']\n",
    "sample_type_vals = data_meta['sample_type'].dropna().unique()\n",
    "\n",
    "# Add X before metadata sampleids to match 16S and 18S sample ids\n",
    "data_meta['sampleid'] = data_meta['sampleid'].apply(lambda x: 'X' + x)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 60.1 ms, sys: 5.66 ms, total: 65.8 ms\n",
      "Wall time: 71.2 ms\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "map_data = pu.compute_map_data(data_meta)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('views/data/map_figure_data.json', 'w') as mapfile:\n",
    "    mapfile.write(json.dumps(map_data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('views/data/map_figure_data.json', 'r') as mapfile:\n",
    "    map_data = json.load(mapfile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 670 ms, sys: 5.68 ms, total: 676 ms\n",
      "Wall time: 676 ms\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "map_figs = pu.precompute_map_figs(map_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 52.6 s, sys: 1.66 s, total: 54.3 s\n",
      "Wall time: 54.5 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "sunburst_data = pu.compute_sunburst_fig_data(data_meta, data_16S, data_18Sv4, data_18Sv9,\n",
    "                                             path=['Phylum', 'Class', 'Order', 'Family'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('views/data/sunburst_data.json', 'w') as sunburstfile:\n",
    "    sunburstfile.write(json.dumps(sunburst_data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('views/data/sunburst_data.json', 'r') as sunburstfile:\n",
    "    sunburst_data = json.load(sunburstfile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 113,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 44.1 s, sys: 1.1 s, total: 45.2 s\n",
      "Wall time: 45.4 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "sunburst_figs = pu.precompute_sunburst_figs(sunburst_data, path=['Phylum', 'Class', 'Order', 'Family'],\n",
    "                                            width=700, height=700)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 24.5 s, sys: 1.88 s, total: 26.4 s\n",
      "Wall time: 25.9 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "stacked_bar_data, colors_16S, colors_18S = pu.compute_stacked_bar_data(data_meta, data_16S, data_18Sv4,\n",
    "                                                                       data_18Sv9)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('views/data/stacked_bar_data.json', 'w') as stackedbarfile:\n",
    "    stacked_bar_write_data = {\n",
    "        'stacked_bar_fig_data': stacked_bar_data,\n",
    "        'colors_16S': colors_16S,\n",
    "        'colors_18S': colors_18S\n",
    "    }\n",
    "    stackedbarfile.write(json.dumps(stacked_bar_write_data))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('views/data/stacked_bar_data.json', 'r') as stackedbarfile:\n",
    "    stacked_bar_data = json.load(stackedbarfile)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 1.12 s, sys: 64.1 ms, total: 1.19 s\n",
      "Wall time: 1.39 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "# precompute stacked bar figures\n",
    "stacked_bar_fig_data, colors_16S, colors_18S = (\n",
    "    stacked_bar_data['stacked_bar_fig_data'],\n",
    "    stacked_bar_data['colors_16S'],\n",
    "    stacked_bar_data['colors_18S']\n",
    ")\n",
    "stacked_bar_figs = pu.precompute_stacked_bar_figs(stacked_bar_fig_data, colors_16S, colors_18S)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 126,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'Figure' object has no attribute 'keys'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[126], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mstacked_bar_figs\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m093.3 030.0\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m16S\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeys\u001b[49m()\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'Figure' object has no attribute 'keys'"
     ]
    }
   ],
   "source": [
    "stacked_bar_figs['093.3 030.0']['16S']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2024-04-08 18:36:23,568] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:24,655] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:25,150] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:25,604] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2024-04-08 18:36:26,781] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:27,769] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:28,191] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:28,644] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2024-04-08 18:36:35,181] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:41,309] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:42,250] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n",
      "[2024-04-08 18:36:43,375] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2024-04-08 18:36:43,713] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 184, in _check_path_in_prop_tree\n",
      "    obj = obj[p]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 728, in __getitem__\n",
      "    prop = BaseFigure._str_to_dict_path(prop)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 1846, in _str_to_dict_path\n",
      "    ret = _str_to_dict_path_full(key_path_str)[0]\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 67, in _str_to_dict_path_full\n",
      "    if len(key_path_str):\n",
      "TypeError: object of type 'int' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 1455, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 869, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 867, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/flask/app.py\", line 852, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/dash.py\", line 1310, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/dash/_callback.py\", line 442, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/by/vpz_wqc14_vgx3vzwgf90gw00000gn/T/ipykernel_18555/1388195188.py\", line 122, in update_sunburst\n",
      "    return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 750, in __getitem__\n",
      "    err = _check_path_in_prop_tree(self, orig_prop, error_cast=PlotlyKeyError)\n",
      "  File \"/Users/michael/anaconda3/lib/python3.10/site-packages/plotly/basedatatypes.py\", line 208, in _check_path_in_prop_tree\n",
      "    if prop[i][0] == \"_\":\n",
      "TypeError: 'int' object is not subscriptable\n"
     ]
    }
   ],
   "source": [
    "def build_app(app):\n",
    "    app.layout = dbc.Container([\n",
    "        html.H1(\"Marine microbial life at California coastal stations\", className=\"mt-4 mb-4\"),\n",
    "        dbc.Row([\n",
    "            dbc.Col([\n",
    "                dbc.Card(\n",
    "                    dbc.CardBody([\n",
    "                        html.Div([\n",
    "                            html.Label('Sample Type:'),\n",
    "                            dcc.Dropdown(sample_type_vals, 'Surf', id='sample-type-dropdown')\n",
    "                        ])\n",
    "                    ])\n",
    "                )\n",
    "            ], width=11.5)\n",
    "        ]),\n",
    "        dbc.Row([\n",
    "            dbc.Col([\n",
    "                dbc.Card(\n",
    "                    dbc.CardBody([\n",
    "                        html.Div([\n",
    "                            html.Label('Environmental Variable (Color):'),\n",
    "                            dcc.Dropdown(['Total Number of Samples'] + env_var_cols, 'Total Number of Samples', id='env-var-dropdown')\n",
    "                        ], className=\"env-var-dropdown\")\n",
    "                    ])\n",
    "                ),\n",
    "                dbc.Card(\n",
    "                    dbc.CardBody([\n",
    "                        html.Div([\n",
    "                            dcc.Graph(id='map-graph')\n",
    "                        ], className=\"map-graph\"),\n",
    "                    ]),\n",
    "                ),\n",
    "                dbc.Card(\n",
    "                    dbc.CardBody([\n",
    "                        html.Div([\n",
    "                            html.Label('Circos Dataset:'),\n",
    "                            dcc.Dropdown(['16S & 18Sv4', '16S & 18Sv9'], '16S & 18Sv4', id='circos-dropdown')\n",
    "                        ]),\n",
    "                        html.Div(id='circos-container', style={'margin-top': '2vw'}),\n",
    "                    ])\n",
    "                ),\n",
    "            ], width=6),\n",
    "            dbc.Col([\n",
    "                dbc.Card(\n",
    "                    dbc.CardBody([\n",
    "                        html.Div([\n",
    "                            html.Label('Dataset:'),\n",
    "                            dcc.Dropdown(['16S', '18Sv4', '18Sv9'], '16S', id='dataset-dropdown')\n",
    "                        ]),\n",
    "                    ])\n",
    "                ),\n",
    "                dbc.Card(\n",
    "                    dbc.CardBody([\n",
    "                        html.Div([\n",
    "                            html.Button('Reset View', id='reset-button')\n",
    "                        ]),\n",
    "                        html.Div([\n",
    "                            dcc.Graph(id='sunburst-graph')\n",
    "                        ]),\n",
    "                    ])\n",
    "                ),\n",
    "                dbc.Card(\n",
    "                    dbc.CardBody([\n",
    "                        html.Div([\n",
    "                            dcc.Graph(id='stacked-bar-graph')\n",
    "                        ])\n",
    "                    ])\n",
    "                )\n",
    "            ], width=6)\n",
    "        ])\n",
    "    ], fluid=True)\n",
    "\n",
    "\n",
    "    # Map graph dropdown callback\n",
    "    @app.callback(\n",
    "        Output('map-graph', 'figure'),\n",
    "        [Input('map-graph', 'clickData'),\n",
    "        Input('sample-type-dropdown', 'value'),\n",
    "        Input('env-var-dropdown', 'value')]\n",
    "    )\n",
    "    def update_map(click_data, dropdown_sample_type, dropdown_env_var):\n",
    "        if click_data is None:\n",
    "            station_id = data_meta['Sta_ID'].iloc[0]\n",
    "        # Get station ID from hover data\n",
    "        else:\n",
    "            if 'customdata' not in click_data['points'][0]:\n",
    "                station_id = data_meta['Sta_ID'].iloc[0]\n",
    "            else:\n",
    "                station_id = click_data['points'][0]['customdata'][0]\n",
    "        cur_fig = go.Figure(map_figs[dropdown_sample_type][dropdown_env_var])\n",
    "        cur_fig.update_layout(\n",
    "            template='plotly_dark',\n",
    "            plot_bgcolor= 'rgba(0, 0, 0, 0)',\n",
    "            paper_bgcolor= 'rgba(0, 0, 0, 0)',\n",
    "            width=600,\n",
    "            height=600\n",
    "        )\n",
    "        stations = cur_fig.data[0]['customdata']\n",
    "        stations = [x[0] for x in stations]\n",
    "        clicked_station_idx = stations.index(station_id)\n",
    "        cur_fig.data[0]['marker']['size'][clicked_station_idx] = 5\n",
    "        return cur_fig\n",
    "        \n",
    "\n",
    "    # Map graph click data callback for sunburst\n",
    "    @app.callback(\n",
    "        Output('sunburst-graph', 'figure'),\n",
    "        [Input('sample-type-dropdown', 'value'),\n",
    "        Input('map-graph', 'clickData'),\n",
    "        Input('dataset-dropdown', 'value'),\n",
    "        Input('reset-button', 'n_clicks')]\n",
    "    )\n",
    "    def update_sunburst(dropdown_sample_type, click_data, dropdown_dataset, n_clicks):\n",
    "        if click_data is None:\n",
    "            station_id = data_meta['Sta_ID'].iloc[0]\n",
    "        # Get station ID from hover data\n",
    "        else:\n",
    "            if 'customdata' not in click_data['points'][0]:\n",
    "                station_id = data_meta['Sta_ID'].iloc[0]\n",
    "            else:\n",
    "                station_id = click_data['points'][0]['customdata'][0]\n",
    "        return sunburst_figs[station_id][dropdown_sample_type][dropdown_dataset].update_layout(\n",
    "            template='plotly_dark',\n",
    "            plot_bgcolor= 'rgba(0, 0, 0, 0)',\n",
    "            paper_bgcolor= 'rgba(0, 0, 0, 0)',\n",
    "            height=800,\n",
    "            width=800\n",
    "        )\n",
    "\n",
    "    # Stacked bar callback\n",
    "    @app.callback(\n",
    "        Output('stacked-bar-graph', 'figure'),\n",
    "        [Input('map-graph', 'clickData'),\n",
    "        Input('dataset-dropdown', 'value')]\n",
    "    )\n",
    "    def update_stacked_bar(click_data, dropdown_dataset):\n",
    "        if click_data is None:\n",
    "            station_id = data_meta['Sta_ID'].iloc[0]\n",
    "        # Get station ID from hover data\n",
    "        else:\n",
    "            if 'customdata' not in click_data['points'][0]:\n",
    "                station_id = station_id = data_meta['Sta_ID'].iloc[0]\n",
    "            else:\n",
    "                station_id = click_data['points'][0]['customdata'][0]\n",
    "        return stacked_bar_figs[station_id][dropdown_dataset].update_layout(\n",
    "            template='plotly_dark',\n",
    "            plot_bgcolor= 'rgba(0, 0, 0, 0)',\n",
    "            paper_bgcolor= 'rgba(0, 0, 0, 0)',\n",
    "            height=600,\n",
    "            width=800\n",
    "        )\n",
    "    @app.callback(\n",
    "        Output('circos-container', 'children'),\n",
    "        [Input('circos-dropdown', 'value')]\n",
    "    )\n",
    "    def update_circos(circos_dropdown):\n",
    "        if circos_dropdown == '16S & 18Sv4':\n",
    "            src_path = 'assets/NCOG_network_v4_chordDiagram_positive.png'\n",
    "        elif circos_dropdown == '16S & 18Sv9':\n",
    "            src_path = 'assets/NCOG_network_v9_chordDiagram_positive.png'\n",
    "        return html.Img(src=src_path, style={\n",
    "            'template':'plotly_dark',\n",
    "            'plot_bgcolor':'rgba(0, 0, 0, 0)',\n",
    "            'paper_bgcolor':'rgba(0, 0, 0, 0)',\n",
    "            'height':600,\n",
    "            'width':600\n",
    "        })"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://0.0.0.0:8095/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x2ec2cc700>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "app = dash.Dash(__name__, external_stylesheets=[dbc.themes.SLATE])\n",
    "port=8095\n",
    "build_app(app)\n",
    "app.run_server(host='0.0.0.0', port=port)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
